### ISSUE TITLE
KeyError: 'rend_alpha'

### ISSUE THREAD

**Issue by denred0** [TingtingLiao/Dream2DGS#7]
Thank you for your work. 
Everything is OK but I've gotten the error during the mesh extraction step. 
```
Traceback (most recent call last):
  File "/content/Dream2DGS/convert.py", line 114, in <module>
    gaussExtractor.reconstruction(cameras)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/Dream2DGS/utils/mesh_utils.py", line 112, in reconstruction
    alpha = render_pkg['rend_alpha']
KeyError: 'rend_alpha'
```
I used your example with the zelda.

**Comment by denred0** [comment]
I've fixed it. Need to replace 
Dream2DGS/utils/mesh_utils.py", line 112
`alpha = render_pkg['rend_alpha']`
with 
`alpha = render_pkg['alpha']`

**Comment by denred0** [comment]
Additionally need to add 
`import cv2`
into Dream2DGS/utils/mesh_utils.py

**Comment by TingtingLiao** [comment]
updated. thank you so much
